import argparse
import os
import sys
from datetime import datetime
from pathlib import Path
from subprocess import call

from dirsync import sync

from lndocs._generate_conf import generate_conf

HERE = Path(__file__).parent


# https://stackoverflow.com/questions/41129921
def datetime_valid(s: str):
    try:
        datetime.fromisoformat(s)
    except ValueError:
        try:  # catch MM-YY dates
            s = "2000-" + s[:5]
            datetime.fromisoformat(s)
        except ValueError:
            return False
    return True


# this here is difficult to test but I hope it's now safe and doesn't
# corrupt html files anymore
def remove_lines_with_db_args(path: Path):
    with open(path) as f:
        content = f.read()
    # now, find the line that contains *db_args and remove it
    previous_line = ""
    found_db_args = False
    for line in content.split("\n")[:700]:
        if (
            "db_args" in line
            and line.endswith("</dt>")
            and previous_line == '<dt class="sig sig-object py">'
        ):
            found_db_args = True
            break
        previous_line = line
    if found_db_args:
        with open(path, "w") as f:
            f.write(content.replace(previous_line + "\n" + line, ""))


def sluggify_autosummary():
    import sphinx.ext.autosummary
    import sphinx.ext.autosummary.generate

    content = Path(sphinx.ext.autosummary.generate.__file__).read_text()
    original_line = (
        "filename = os.path.join(path, filename_map.get(name, name) + suffix)"
    )
    new_line = (
        "filename = os.path.join(path, filename_map.get(name, name).lower() + suffix)"
    )
    if original_line not in content:
        assert new_line in content
    else:
        Path(sphinx.ext.autosummary.generate.__file__).write_text(
            content.replace(original_line, new_line)
        )

    content = Path(sphinx.ext.autosummary.__file__).read_text()
    original_line = "real_name = filename_map.get(real_name, real_name)"
    new_line = "real_name = filename_map.get(real_name, real_name).lower()"
    if original_line not in content:
        assert new_line in content
    else:
        Path(sphinx.ext.autosummary.__file__).write_text(
            content.replace(original_line, new_line)
        )


ORIG_ANSI = """\
                        elif value == 49:
                            self.bg_color = None"""

NEW_ANSI = '''\
                        elif value == 49:
                            self.bg_color = None
                        elif value == 92:  # Special case for bright green
                            self.fg_color = "Green"
                        elif value == 94:  # Special case for bright blue
                            self.fg_color = "Blue"'''


def additional_ansi_colors():
    import myst_nb.core.lexers

    content = Path(myst_nb.core.lexers.__file__).read_text()
    if NEW_ANSI not in content:
        assert ORIG_ANSI in content
        Path(myst_nb.core.lexers.__file__).write_text(
            content.replace(ORIG_ANSI, NEW_ANSI)
        )


def main():
    parser = argparse.ArgumentParser(description="Build Lamin website.")
    aa = parser.add_argument
    aa("--show", action="store_true", help="launch server & show")
    aa("--docs", type=str, default="docs", help="directory with docs sources")
    aa("--site", type=str, default="_build/html", help="output directory")
    aa("--live", action="store_true", help="use autobuild")
    aa("--strict", action="store_true", help="error upon warning")
    aa(
        "--error-on-index",
        action="store_true",
        help=(
            "error if encountering nested index files (needed for composite Next.js"
            " site)"
        ),
    )
    aa("--strip-prefix", action="store_true", help="error upon warning")
    aa("--clean", action="store_true", help="clean build directory")
    args = parser.parse_args()

    if args.clean:
        paths_to_delete = ["lamin_sphinx", "_docs_tmp"]
        for path in paths_to_delete:
            path = Path(f"{Path.getcwd()}/{path}")
            print(f"Removing directory: {path}")
            import shutil

            shutil.rmtree(path)

        return

    if not Path(args.docs).exists():
        sys.exit(
            f"The source directory {args.docs} does not exist! Change to repo root!"
        )

    sync(str(HERE / "lamin_sphinx"), "./lamin_sphinx", "sync", create=True, ctime=True)
    # check whether we need to generate the conf.py for Sphinx
    # input for it is the lamin-project.yaml file
    generate_conf_check = False
    conf_file = Path(args.docs) / "conf.py"
    if not conf_file.exists():
        generate_conf_check = True
    else:
        with open(conf_file) as f:
            first_line = f.readline()
        if first_line == "# auto-generated by lndocs\n":
            generate_conf_check = True
    if generate_conf_check:
        generate_conf(args.docs)

    if args.live:
        build_command = "sphinx-autobuild"
    else:
        build_command = "sphinx-build"

    docs_dir = Path(f"_{args.docs}_tmp/")
    sync(
        args.docs,
        docs_dir,
        "sync",
        create=True,
    )
    for path in docs_dir.glob("**/*"):
        if args.error_on_index:
            if path.name == "index.md" and not path == docs_dir / "index.md":
                raise ValueError(f"Please replace {path} with {path.parent}.md")
        if path.suffix not in {".md", ".ipynb"}:
            continue
        if ".ipynb_checkpoints/" in str(path):
            continue
        if path.suffix == ".ipynb" and args.strip_prefix:
            # test whether prefix is capital letter or digit and if so,
            # strip them for pretty & persistent urls
            # we need the prefixes
            # on notebooks to allow users to navigate downloaded notebooks
            # that should display in order in a file browser
            # ignore dates!
            prefix = path.stem[0]
            if not datetime_valid(path.stem[:10]) and (
                prefix.isdigit() or prefix.isupper() and "-" in path.stem
            ):
                new_stem = "-".join(path.stem.split("-")[1:])
                # path.with_stem() is >3.9
                new_path = path.with_name(f"{new_stem}{path.suffix}")
                path.rename(new_path)

    sluggify_autosummary()
    additional_ansi_colors()

    if args.strict:
        os.environ["LNDOCS_WARNING_IS_ERROR"] = "1"
    build_status = call(f"{build_command} {docs_dir} {args.site}", shell=True)
    if args.strict:
        del os.environ["LNDOCS_WARNING_IS_ERROR"]

    # remove db_args from registries documentation
    for package_name in [
        "lamindb",
        "bionty",
        "omop",
        "lrex",
        "wetlab",
        "findrefs",
        "ourprojects",
        "cellregistry",
    ]:
        for generated in Path(docs_dir).glob(f"{package_name}.*.rst"):
            remove_lines_with_db_args(
                Path(args.site) / generated.with_suffix(".html").name
            )

    if not args.show:
        return build_status
    else:
        if build_status == 0:
            call("python -m http.server", shell=True, cwd="./_build/html")
