import argparse
import sys
from datetime import datetime
from pathlib import Path
from subprocess import call

import yaml  # type: ignore
from dirsync import sync

from lndocs._generate_conf import generate_conf

HERE = Path(__file__).parent


def get_lamin_project():
    with open("./lamin-project.yaml") as f:
        try:
            return yaml.safe_load(f)
        except yaml.YAMLError as exc:
            print(exc)
            quit()


# https://stackoverflow.com/questions/41129921
def datetime_valid(s: str):
    try:
        datetime.fromisoformat(s)
    except ValueError:
        return False
    return True


def main():
    parser = argparse.ArgumentParser(description="Build Lamin website.")
    aa = parser.add_argument
    aa("--show", action="store_true", help="launch server & show")
    aa("--docs", type=str, default="docs", help="directory with docs sources")
    aa("--site", type=str, default="_build/html", help="output directory")
    aa("--live", action="store_true", help="use autobuild")
    args = parser.parse_args()
    if not Path(args.docs).exists():
        sys.exit(
            f"The source directory {args.docs} does not exist! Change to repo root!"
        )
    if not Path("./lamin-project.yaml").exists():
        sys.exit("The ./lamin-project.yaml conf file does not exist!")
    lamin_project = get_lamin_project()

    sync(str(HERE / "lamin_sphinx"), "./lamin_sphinx", "sync", create=True, ctime=True)
    # check whether we need to generate the conf.py for Sphinx
    # input for it is the lamin-project.yaml file
    generate_conf_check = False
    conf_file = Path(args.docs) / "conf.py"
    if not conf_file.exists():
        generate_conf_check = True
    else:
        with open(conf_file) as f:
            first_line = f.readline()
        if first_line == "# auto-generated by lndocs\n":
            generate_conf_check = True
    if generate_conf_check:
        generate_conf(args.docs)

    if args.live:
        build_command = "sphinx-autobuild"
    else:
        build_command = "sphinx-build"

    docs_dir = Path(f"_{args.docs}_tmp/")
    sync(
        args.docs,
        docs_dir,
        "sync",
        create=True,
    )
    for path in docs_dir.glob("**/*"):
        if path.suffix not in {".md", ".ipynb"}:
            continue
        if ".ipynb_checkpoints/" in str(path):
            continue
        if path.suffix == ".ipynb":
            # test whether prefix is capital letter or digit and if so,
            # strip them for pretty & persistent urls
            # we need the prefixes
            # on notebooks to allow users to navigate downloaded notebooks
            # that should display in order in a file browser
            # ignore dates!
            prefix = path.stem[0]
            if not datetime_valid(path.stem[:10]) and (
                prefix.isdigit() or prefix.isupper() and "-" in path.stem
            ):
                new_stem = "-".join(path.stem.split("-")[1:])
                # path.with_stem() is >3.9
                new_path = path.with_name(f"{new_stem}{path.suffix}")
                path.rename(new_path)

    build_status = call(f"{build_command} {docs_dir} {args.site}", shell=True)

    # delete auto-generated files
    if "package_name" in lamin_project:
        package_name = lamin_project["package_name"]
        for generated in Path(args.docs).glob(f"{package_name}.*.rst"):
            generated.unlink()

    if not args.show:
        return build_status
    else:
        if build_status == 0:
            call("cd _build/html; python -m http.server", shell=True)
