import argparse
import sys
from pathlib import Path
from subprocess import call

from dirsync import sync

from lndocs._generate_conf import generate_conf

HERE = Path(__file__).parent


def main():
    parser = argparse.ArgumentParser(description="Build Lamin website.")
    aa = parser.add_argument
    aa("--docs", type=str, default="docs", help="directory with docs sources")
    aa("--site", type=str, default="_build/html", help="output directory")
    aa("--live", action="store_true", help="use autobuild")
    aa("--show", action="store_true", help="launch server & show")
    args = parser.parse_args()
    sync(str(HERE / "lamin_sphinx"), "./lamin_sphinx", "sync", create=True)

    if not Path(args.docs).exists():
        sys.exit(f"The source directory {args.docs} does not exist!")

    # check whether we need to generate the conf.py for Sphinx
    # input for it is the lamin-project.yaml file
    generate_conf_check = False
    conf_file = Path(args.docs) / "conf.py"
    if not conf_file.exists():
        generate_conf_check = True
    else:
        with open(conf_file) as f:
            first_line = f.readline()
        if first_line == "# auto-generated by lndocs\n":
            generate_conf_check = True
    if generate_conf_check:
        generate_conf(args.docs)

    if args.live:
        build_command = "sphinx-autobuild"
    else:
        build_command = "sphinx-build"

    build_status = call(f"{build_command} {args.docs} {args.site}", shell=True)

    if not args.show:
        return build_status
    else:
        if build_status == 0:
            call("cd _build/html; python -m http.server", shell=True)
