# auto-generated by lndocs
import sys
from pathlib import Path

try:
    import {{ lamin_package_name }}

    release = {{ lamin_package_name }}.__version__
except ImportError:
    print("there is no python package: {{ lamin_package_name }}")

HERE = Path(__file__).parent
sys.path[:0] = [str(HERE), str(HERE.parent)]
from lamin_sphinx import *  # noqa
from lamin_sphinx import html_context, html_theme_options

project = "{{ lamin_project_name }}"
html_title = "{{ lamin_project_name }} | Lamin"
html_context["github_repo"] = "{{ lamin_repository_name }}"  # noqa

ogp_site_url = "https://{{ lamin_project_slug }}.lamin.ai/"
ogp_site_name = project

html_theme_options["logo"] = {
    "link": ogp_site_url,
    "text": project,
    "root": "https://lamin.ai"
}
html_theme_options["icon_links"] = [
    {
        "name": "GitHub",
        "url": "https://github.com/laminlabs/{{ lamin_repository_name }}",
        "icon": "fa-brands fa-github",
    },
]
